## basic syntax

In [2]:
import tensorflow as tf

In [3]:
# word tensor is a ndimensional array
hello = tf.constant("hello")
world = tf.constant(" world")

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)
# we can't directly run tensor 
# we need a session

Tensor("Const:0", shape=(), dtype=string)


In [10]:
with tf.Session() as sess:
    result = sess.run(hello+world)

# Session is similar to a  file it need to closed 

In [11]:
print(result)

b'hello world'


* Opertaions 

In [15]:
a = tf.constant(10)
b = tf.constant(1)
print("type of a is ", type(a), "\n")
with tf.Session() as sess:
    print("sum is ",sess.run(a+b))

type of a is  <class 'tensorflow.python.framework.ops.Tensor'> 

sum is  11


- tensorflow is similar to numpy
- numpy creates nd array and tensorflow creats nd tensors

In [25]:
const = tf.constant(3) # a constant

fil_mat = tf.fill((4, 4), 2) # 4X4 matrix filled with ones

zero = tf.zeros((4, 4)) # matrix with zeros
one = tf.ones(4, 4) #ones

rand_norm = tf.random_normal((4, 4), mean = 0, stddev= 0.4) # normal distribution

rand_uni = tf.random_uniform((4, 4), minval = 0 , maxval = 15) # uniform distribution

- we usually use with Session() as sess:
- but ipynb has interactive mode that keeps session active on entire notebook

In [26]:
sess = tf.InteractiveSession()

In [28]:
l =[const, fil_mat, zero, one, rand_norm, rand_uni]
for obj in l:
    print(sess.run(obj), '\n')
    
# once again interactive session works only on jupyter notebook

3 

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]] 

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]] 

[1 1 1 1] 

[[-0.06138824 -0.56423253  0.21484803 -0.23428564]
 [ 0.2412632   0.01093897  0.59810513 -0.00944217]
 [ 0.00275855 -0.22687896 -0.68629301  0.40522501]
 [-1.67462862  0.486931   -0.39862299  0.20518576]] 

[[ 10.61816788  13.72140026  12.67614269   6.03772068]
 [ 12.82941151   0.52316844   3.94951344   7.30294514]
 [  4.42410183  14.02230263   7.83962488  12.35296535]
 [ 11.81871796  13.10065269   2.36957431  14.26127529]] 



In [29]:
mat1 = tf.constant([[1, 2],
                    [3, 4]])

mat2 = tf.constant([[3],
                    [5]])

In [33]:
print(mat1.get_shape(), mat2.get_shape())

(2, 2) (2, 1)


In [38]:
# matrix multiplication
mul = tf.matmul(mat1, mat2)
print(sess.run(mul))
# you can also use eval method
print('\n', mul.eval())

[[13]
 [29]]

 [[13]
 [29]]


## Graphs

In [39]:
n1 = tf.constant(4)
n2 = tf.constant(3)
n3 = n1 + n2
# all these are stored in the form of node

In [41]:
n3.eval()

7

In [43]:
print(n2)

Tensor("Const_15:0", shape=(), dtype=int32)


In [44]:
# all this work is done intenally in graph 
print(tf.get_default_graph())

In [48]:
# we can create our own graph
g = tf.Graph()
print(g)

In [50]:
graph2 = tf.get_default_graph()
print(graph2)

In [51]:
# you can set your graph as default
with g.as_default():
    print(g is tf.get_default_graph())

True


In [53]:
print(g is tf.get_default_graph())
# default graphs exits only with in the scope of session

False


Variables and place holder

In [54]:
# variables need to be intialed befor running session
# place holder need to no data type and size

In [8]:
sess = tf.InteractiveSession()

In [9]:
ten = tf.random_uniform((4, 4), 0, 0.5)
var = tf.Variable(initial_value= ten)

In [10]:
# You need to initial it first
init = tf.global_variables_initializer()

In [12]:
sess.run(init)
sess.run(var)

array([[ 0.06688541,  0.17735052,  0.2672224 ,  0.02910304],
       [ 0.2728138 ,  0.46080071,  0.13473171,  0.34500384],
       [ 0.00224918,  0.47596723,  0.3899346 ,  0.11672169],
       [ 0.16384679,  0.39257121,  0.22297883,  0.129085  ]], dtype=float32)

In [22]:
ph = tf.placeholder(tf.float16, shape=(1, 2))